### PR TITLE
Fix for issue #26 (config.set_request_property)

### PR DESCRIPTION
**Pull request by jjmurre**
config.set_request_property now crashes in pyramid,
needs to be config.add_request_method.

### CODE REVIEW

**Comment by stevepiercy** [comment]
The tests are failing due to a flake8 issue with regular expressions, even if they are in docstrings. This is not due to this PR. See fix: https://lintlyci.github.io/Flake8Rules/rules/W605.html I created issue #28 to track it.

**Comment by maarten-vermeyen** [comment]
Is there any chance of this getting into a release? It seems to me that a breaking incompatibility with the stable release of pyramid is something we should address. 

Is #28 the only thing blocking this, or does the change somehow break backwards compatibility with older versions of pyramid?

**Comment by stevepiercy** [comment]
@maarten-vermeyen one of the [maintainers](https://pypi.org/project/pyramid_ldap/) would need to merge and cut a release.

Meanwhile, if you have some time, it would be nice to also get a fix for #28 to silence the flake8 warning for review, merge, and release at the same time. It looks like a [quick and easy fix](https://travis-ci.org/Pylons/pyramid_ldap/jobs/519138998#L477-L481).

**Comment by bertjwregeer** [comment]
ping @chrismorales

**Comment by digitalresistor** [comment]
I believe this has been fixed with the merging of #33.

**Pull request closed without merging**
