### PR TITLE
Replace config.set_request_property by config.add_request_method

### PR DESCRIPTION
**Pull request by arnaud-morvan**
For compatibility with pyramid 1.10

### CODE REVIEW

**Review by mmerickel — APPROVED** [review]

**Comment by stevepiercy** [comment]
@arnaud-morvan there is a [failing test in the build](https://travis-ci.org/github/Pylons/pyramid_ldap/jobs/672472364#L246) that needs to be fixed.

**Comment by arnaud-morvan** [comment]
@mmerickel @stevepiercy : Thanks for review, I fixed the test, seems that pep8 errors are not related with the PR but already in master.
Could you have a look at : https://github.com/Pylons/pyramid_ldap/pull/29

**Comment by digitalresistor** [comment]
Would you mind rebasing this change on master?

**Comment by digitalresistor** [comment]
Actually I believe this was fixed in #33, please re-open if not the case.

**Pull request closed without merging**
