### PR TITLE
Travis setup and RTD fixes

### PR DESCRIPTION
**Pull request by stevepiercy**
This PR adds Travis CI and fixes broken RTD builds.

### CODE REVIEW

**Comment by stevepiercy** [comment]
Well, I got as far as I understand at this moment. `six` is installed, but the import error says it cannot find the module. I could use an assist.

**Comment by bertjwregeer** [comment]
How and where is six installed? I don't see it being installed in that tox output. It likely needs an explicit dependency on six to be added because it is missing from ldappool: https://github.com/Pylons/pyramid_ldap/pull/21/files#diff-2eeaed663bd0d25b7e608891384b7298R16

**Comment by bertjwregeer** [comment]
That's for the `tox` installation, not for the installation of `pyramid_ldap` inside the environment `tox` creates for testing `pyramid_ldap`.

**Comment by bertjwregeer** [comment]
👍 @stevepiercy

**Comment by stevepiercy** [comment]
Of course the py3 environments fail, pending the merge of #21, but at least the py27 and docs envs pass. Dunno if we care about PEP8. I'd appreciate a review and feedback.

**Comment by stevepiercy** [comment]
py27 tests pass.

RTD builds successfully now, too.

Merging now.

#21 should take care of the py36 failures. Then I'll come back around and clean up the PEP8 failures.

**Pull request merged**
